title: Amara — Data Portfolio
description: >-
  Data science portfolio showcasing projects, analysis, and visualizations.
author: Amara Nwokedinobi
email: dominus.amara@gmail.com
github_username: Amararunsdata
linkedin_url: "https://www.linkedin.com/in/amara-nwokedinobi/"


url: "https://Amararunsdata.github.io"
baseurl: ""

markdown: kramdown
sass:
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
